### PR TITLE
Production server update

### LINKED ISSUE #183: ClickHouse memory issue
From Backend server log
Image

ClickHouse error logs:
```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f88f17b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009da318c
2. DB::Exception::Exception<char const*, char const*, String, String, String, String, String, char const*, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<char const*>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<char const*>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, char const*&&, char const*&&, String&&, String&&, String&&, String&&, String&&, char const*&&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000000f8feab2
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f8fcc96
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f8fc3ce
5. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f8fc3ce
6. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f8fc3ce
7. CurrentMemoryTracker::allocImpl(long, bool) @ 0x000000000f862ae5
8. Allocator<false, false>::alloc(unsigned long, unsigned long) @ 0x000000000f86050a
9. DB::Memory<Allocator<false, false>>::alloc(unsigned long) @ 0x000000000f95626d
10. DB::WriteBufferFromFileDescriptor::WriteBufferFromFileDescriptor(int, unsigned long, char*, std::shared_ptr<DB::Throttler>, unsigned long, String, bool, unsigned long) @ 0x000000000f97d408
11. DB::WriteBufferFromFile::WriteBufferFromFile(String const&, unsigned long, int, std::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long, bool, unsigned long) @ 0x000000000faa7bfc
12. DB::DiskLocal::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x0000000012da4520
13. DB::DataPartStorageOnDiskFull::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x00000000147952a8
14. DB::MergeTreeDataPartWriterOnDisk::Stream<false>::Stream(String const&, std::shared_ptr<DB::IDataPartStorage> const&, String const&, String const&, String const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, DB::WriteSettings const&) @ 0x00000000149a8695
15. void std::__function::__policy_invoker<void (DB::ISerialization::SubstreamPath const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IAST> const&)::$_0, void (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x00000000149b9f3d
16. DB::SerializationSparse::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x0000000012b6dda6
17. DB::ISerialization::enumerateStreams(std::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::shared_ptr<DB::IDataType const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) const @ 0x0000000012af1968
18. DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IAST> const&) @ 0x00000000149b11ff
19. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, std::shared_ptr<DB::MergeTreeIndexGranularity>) @ 0x00000000149b0f65
20. DB::createMergeTreeDataPartWideWriter(String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, std::shared_ptr<DB::MergeTreeIndexGranularity>) @ 0x0000000014998662
21. DB::createMergeTreeDataPartWriter(DB::MergeTreeDataPartType, String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::unordered_map<String, unsigned long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, unsigned long>>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, std::shared_ptr<DB::MergeTreeIndexGranularity>) @ 0x00000000148903a8
22. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::shared_ptr<DB::IMergeTreeDataPart> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, std::shared_ptr<DB::ICompressionCodec>, std::shared_ptr<DB::MergeTreeIndexGranularity>, DB::TransactionID, unsigned long, bool, bool, DB::WriteSettings const&) @ 0x0000000014b1a4ed
23. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x0000000014860a37
24. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x00000000148691ae
25. DB::MergeTask::execute() @ 0x0000000014873642
26. DB::MergePlainMergeTreeTask::executeStep() @ 0x0000000014cc4b0e
27. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001489a7ed
28. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000000f9cb78b
29. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000f9d23a3
30. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000f9c89b2
31. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f9cfe7a
 (version 25.5.2.47 (official build))
2025.06.11 12:43:03.560913 [ 650 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {124e6fea-22bd-421a-bc7b-432abaa37535::202506_30273_42678_199}: Code: 241. DB::Exception: (total) memory limit exceeded: would use 3.36 GiB (attempt to allocate chunk of 4.16 MiB bytes), current RSS: 1.41 GiB, maximum: 3.36 GiB. (MEMORY_LIMIT_EXCEEDED) 
```

### LINKED ISSUE #184: Server fails to update GeoIp
Image

### LINKED ISSUE #185: IP forwarding not functioning properly
All read IPs on server is local IP - suspect real IP is getting stripped at reverse proxy level

Image

### LINKED ISSUE #186: ClickHouse volume size is much larger than expected
ClickHouse volume takes up more than 7GB after a few days taking in only a few requests.
This is probably due to logs being stored in table.
Image

### PR DESCRIPTION
**Pull request by flopper123**
Closes #183 
Closes #186 
Closes #185 
Closes #184

ClickHouse config updates:
- Reduce log sizes
- Optimize setup for less than 16GB available ram

NGINX updates:
- Ensure correct port forwarding

Backend:
- Ensure correct packages are installed to get GeoIp
- Ensure IP is parsed from proxy defined header instead of direct IP

### CODE REVIEW

File: clickhouse-config/config.d/config.xml [hunk 1]
```diff
@@ -1,15 +1,41 @@
 <clickhouse>
+  <!-- Logging setup -->
   <logger>
-    <level>debug</level>
+    <level>notice</level>
```
Comment (Lindharden) [inline clickhouse-config/config.d/config.xml:4]: What are the benefits of keeping logging level at "notice" instead of "warning"?

**Review by Lindharden — DISMISSED** [review]

File: clickhouse-config/config.d/config.xml (hunk 1 above)
Comment (flopper123) [reply clickhouse-config/config.d/config.xml:4]: Just in case there's additional logs we might want to catch.
We can always bump it up to "warning" if everything goes great 😄

File: backend/src/main.rs [hunk 2]
```diff
@@ -117,6 +117,22 @@ async fn track_event(
...
+            if let Some(first_ip) = forwarded_str.split(',').next() {
+                if let Ok(ip) = IpAddr::from_str(first_ip.trim()) {
+                    return ip;
+                }
+            }
+        }
+    }
+
+    // Fallback to localhost IP
+    "127.0.0.1".parse().unwrap()
```
Comment (Lindharden) [inline backend/src/main.rs:133]: Wouldn't it be more flexible to fallback to the old IP parsing so that it technically also works without the nginx routing?

**Review by Lindharden — CHANGES_REQUESTED** [review]
Looks good :)

File: dashboard/src/contexts/QueryFiltersContextProvider.tsx [hunk 3]
```diff
@@ -4,7 +4,7 @@ import { useQueryFilters } from '@/hooks/use-query-filters';
 
 type QueryFiltersContextProps = {
   queryFilters: QueryFilter[];
-  addQueryFilter: Dispatch<QueryFilter>;
+  addQueryFilter: Dispatch<QueryFilter | Omit<QueryFilter, 'id'>>;
```
[the remark this answers is not in the document]
Comment (flopper123) [reply dashboard/src/contexts/QueryFiltersContextProvider.tsx:7]: Yeah, I added this to compile the `TabbedPagesTable`:
image

The `addQueryFilter` from the hook will give the filter an id, only if no id is passed. So I updated the type of `addQueryFilter` to reflect this 😄

File: backend/src/main.rs (hunk 2 above)
Comment (flopper123) [reply backend/src/main.rs]: Updated
