### PR TITLE
Funnel page improvements

### LINKED ISSUE #151: Apply proper theme variables to funnels
Funnels are missing theme styling variables:

Image

Additionally, the progress bar in live preview uses the wrong color scheme:

Image

It should be blue (primary color)

### PR DESCRIPTION
**Pull request by flopper123**
### UI/UX improvements
Added cleaner empty state
image

Added dark mode for funnels page + UI improvements:
image

Closes #151

### CODE REVIEW

File: dashboard/src/contexts/OpenContextProvider.tsx [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+export function OpenProvider({ children }: Props) {
+  const openHandler = useOpen();
+  return <OpenContext.Provider value={openHandler}>{children}</OpenContext.Provider>;
+}
+
+export function useOpenContext() {
+  const context = useContext(OpenContext);
+  if (!context) throw new Error('useOpenContext must be used within OpenProvider');
+  return context;
+}
```
Comment (Lindharden) [inline dashboard/src/contexts/OpenContextProvider.tsx:23]: What's this for?

Comment (flopper123) [reply dashboard/src/contexts/OpenContextProvider.tsx:23]: It's a generic "open" context - It's used to open the CreateFunnelDialog from a separate component than where it's placed. Can probably be done in a cleaner way

File: dashboard/src/hooks/use-open.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+  }, []);
+
+  return {
+    isOpen,
+    setIsOpen,
+    open,
+    close,
+    toggle,
+  };
+}
```
Comment (Lindharden) [inline dashboard/src/hooks/use-open.ts:25]: This seems unused

**Comment by flopper123** [comment]
Updated dialog:
- Now has a max size set
- Moved text to the right and no text between progress bars
- Removed duplicate values
- Ensures there's always at least one empty filter

image

File: dashboard/src/app/dashboard/[dashboardId]/funnels/CreateFunnelDialog.tsx [hunk 3]
```diff
@@ -12,186 +12,159 @@ import {
...
+import { type FunnelPreview } from '@/entities/funnels';
+import { useDebounce } from '@/hooks/useDebounce';
+import { useQueryFilters } from '@/hooks/use-query-filters';
+import { QueryFilterInputRow } from '@/components/filters/QueryFilterInputRow';
 
 type Page = {
   value: string;
   key: string;
-}
+};
```
Comment (Lindharden) [inline dashboard/src/app/dashboard/[dashboardId]/funnels/CreateFunnelDialog.tsx:32]: Unused

File: dashboard/src/lib/analytics.ts [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+  const conversionRate = visitorCount.min / (visitorCount.max || 1);
+
+  return {
+    visitorCount,
+    steps,
+    biggestDropOff,
+    conversionRate,
+  };
+}
```
Comment (Lindharden) [inline dashboard/src/lib/analytics.ts:42]: This seems like something that belongs in a service rather than a lib file

**Review by Lindharden — CHANGES_REQUESTED** [review]
Looks better. Left some minor comments :)

**Comment by Lindharden** [comment]
I dont know if my comment got lost, can't find it myself. But the "Create Funnel" dialog is squished:

image


Additionally, a NaN appears for empty paths

File: dashboard/src/lib/analytics.ts (hunk 4 above)
Comment (flopper123) [reply dashboard/src/lib/analytics.ts:42]: Rewrote as a presenter 😄

File: dashboard/src/app/dashboard/[dashboardId]/funnels/CreateFunnelDialog.tsx [hunk 5]
```diff
@@ -12,186 +12,153 @@ import {
...
-    postFunnelAction(
-      dashboardId,
-      funnel.name,
-      funnel.pages.map((f) => f.value),
-      funnel.isStrict
-    )
+    postFunnelAction(dashboardId, metadata.name, queryFilters, metadata.isStrict)
       .then(() => {
         toast.success('Funnel created!');
         queryClient.invalidateQueries({ queryKey: ['funnels', dashboardId] });
```
Comment (Lindharden) [inline dashboard/src/app/dashboard/[dashboardId]/funnels/CreateFunnelDialog.tsx:77]: Is this necessary now that we streaming the data using promises?

File: dashboard/src/components/funnels/Funnel.tsx
Comment (Lindharden) [inline dashboard/src/components/funnels/Funnel.tsx:1]: Noice but lets rename it so that the component name matches the exported function, otherwise navigation becomes difficult for me hehe :)

**Review by Lindharden — CHANGES_REQUESTED** [review]
Niiice almost there !

**Review by Lindharden — APPROVED** [review]
