### PR TITLE
Remove redundant 'Update Profile' button from User Settings

### LINKED ISSUE #620: Remove redundant 'Update Profile' button from User Settings
## Description:

The User Settings modal has inconsistent save behavior. The Profile tab has its own "Update Profile" button to save username/email changes, while all other tabs use the modal's "Save Settings" button. This is confusing for users and inconsistent UX.

* *Current behavior*: Profile tab requires clicking "Update Profile" button to save changes.
* *Expected behavior*: Profile changes should be saved via the "Save Settings" button, consistent with other tabs.

## How to reproduce:

1. Open User Settings modal
2. Go to Profile tab
3. Notice the "Update Profile" button
4. Compare with other tabs that use the modal's "Save Settings" button

## What needs to be done:

- Remove the "*Update Profile*" button from the Profile tab
- Include profile fields (username, email) in the "*Save Settings*" button logic
- Track profile changes in the existing "*unsaved changes*" state

## Screenshot:
Image

### PR DESCRIPTION
**Pull request by evanyang1**
solves #620

### CODE REVIEW

File: dashboard/src/components/userSettings/UserProfileSettings.tsx [hunk 1]
```diff
@@ -1,84 +1,38 @@
...
-import { ZodError } from 'zod';
-import { updateUserAction } from '@/app/actions/account/userSettings.action';
 import SettingsCard from '@/components/SettingsCard';
-import { Button } from '@/components/ui/button';
 import { Input } from '@/components/ui/input';
 import { Label } from '@/components/ui/label';
-import { UpdateUserData, UpdateUserSchema } from '@/entities/auth/user.entities';
 import { useTranslations } from 'next-intl';
-import useIsChanged from '@/hooks/use-is-changed';
+import { UserSettingsUpdate } from '@/entities/account/userSettings.entities';
```
Comment (Woldbye) [inline dashboard/src/components/userSettings/UserProfileSettings.tsx]:
```suggestion
import type { UserSettingsUpdate } from '@/entities/account/userSettings.entities';
```

Prefer type imports when possible

File: dashboard/src/components/userSettings/UserSettingsDialog.tsx [hunk 2]
```diff
@@ -167,30 +175,50 @@ function UserSettingsDialogContent({
...
   const availableTabs = USER_SETTINGS_TABS.filter((tab) => !tab.disabled);
   const [activeTab, setActiveTab] = useState(availableTabs[0].id);
-  const [formData, setFormData] = useState<UserSettingsUpdate>({ ...settings });
+  const [formData, setFormData] = useState<UserSettingsFormData>({
+    ...settings,
+    name: session?.user?.name ?? '',
+  });
   const { refreshSession } = useSessionRefresh();
-  const isFormChanged = useIsChanged(formData, settings);
+  const isSettingsChanged = useIsChanged(formData, { ...settings, name: session?.user?.name ?? '' });
```
Comment (Woldbye) [inline dashboard/src/components/userSettings/UserSettingsDialog.tsx]:
```suggestion
  const originalData = useMemo(() => ({ ...settings, name: session?.user?.name ?? '' }), [settings, session?.user?.name]);
  const isSettingsChanged = useIsChanged(formData, originalData);
```
Quibble: Need to memoize the original data, or isSettingsChanged will get recomputed on every render.

File: dashboard/src/components/userSettings/UserProfileSettings.tsx [hunk 3]
```diff
@@ -1,84 +1,38 @@
...
-            fieldErrors[err.path[0] as keyof UpdateUserData] = err.message;
-          }
-        });
-        setErrors(fieldErrors);
-      }
-    }
-  };
+interface UserProfileSettingsProps {
+  formData: UserSettingsUpdate & { name?: string | null };
+  onUpdate: (updates: Partial<UserSettingsUpdate & { name?: string | null }>) => void;
```
Comment (Woldbye) [inline dashboard/src/components/userSettings/UserProfileSettings.tsx]: `UserSettingsDialog` already have this type declared inline `type UserSettingsFormData = UserSettingsUpdate & { name?: string | null; };`

Lets declare it once in `userSettings.entities.ts` and import it from there to both components.

This approach ensures the types stay in sync

**Review by Woldbye — COMMENTED** [review]
Hey Evan! Glad to see you back on the project.

I had a chance to review your PR - functionally it works as it should but I had a few minor code comments.

One additional comment:  I would appreciate if you could rename the PR to something more appropriate (remember the title effectively becomes the commit message, so need to keep it clean). Something like `Unify profile save with settings dialog` or simply the title of the issue `Remove redundant 'Update Profile' button from User Settings` works for me.

File: dashboard/src/components/userSettings/UserProfileSettings.tsx [hunk 4]
```diff
@@ -1,84 +1,38 @@
...
```
Comment (Woldbye) [inline dashboard/src/components/userSettings/UserProfileSettings.tsx]:
```suggestion
  formData: UserSettingsFormData;
  onUpdate: (updates: Partial<UserSettingsFormData>) => void;
```

Lets use the type you have added to entities! :D 

This should let you remove the import of UserSettingsUpdate all together, and instead import `UserSettingsFormData` from `userSettings.entities.ts`.

**Review by Woldbye — COMMENTED** [review]
I had a change to review the PR! I had one small suggestion on the type import, and a request for handling empty names.

We allow changing name to white space or empty, which causes some inconsistencies in the UI (see below GIF). To resolve this I'd suggest .disabling the Save button (or show a validation message) when the name is trimmed to empty? Simplest approach would be adding a check to the disabled prop on the Save button, or validating in handleSave before the API calls.
Image

File: dashboard/src/components/userSettings/UserSettingsDialog.tsx [hunk 5]
```diff
@@ -245,7 +273,7 @@ function UserSettingsDialogContent({
           <Button variant='outline' onClick={() => handleOpenChange(false)} className='cursor-pointer'>
             {tDialog('buttons.cancel')}
           </Button>
-          <Button onClick={handleSave} disabled={isSaving || !isFormChanged} className='cursor-pointer'>
+          <Button onClick={handleSave} disabled={isSaving || !isSettingsChanged || formData.name === ''} className='cursor-pointer'>
```
Comment (Woldbye) [inline dashboard/src/components/userSettings/UserSettingsDialog.tsx]:
```suggestion
          <Button onClick={handleSave} disabled={isSaving || !isSettingsChanged || formData.name?.trim() === ''} className='cursor-pointer'>
```

Should trim here to keep comparison in sync with how we actually handle the input.

**Review by Lindharden — APPROVED** [review]
Well done 👏
