### PR TITLE
double fetch

### LINKED ISSUE #618: Event Log's infinite scroll double fetches on scroll
## Description:
When scrolling to the bottom of the Event Log, two pages are fetched in quick succession before the first page is rendered. This results in loading 50 events instead of 25.

## How to reproduce:
  1. Navigate to Events page
  2. Scroll to bottom of Event Log
  3. Observe network requests - two fetches fire before first results appear

## Demo
Image

### PR DESCRIPTION
**Pull request by evanyang1**
Closes #618

### CODE REVIEW

File: dashboard/src/app/(protected)/dashboard/[dashboardId]/events/EventLog.tsx [hunk 1]
```diff
@@ -144,20 +160,19 @@ export function EventLog({ pageSize = DEFAULT_PAGE_SIZE }: EventLogProps) {
...
-                })}
+                {allEvents.map((event: EventLogEntry, index: number) => (
+                  <EventLogItem
+                    key={`${event.timestamp}-${index}`}
+                    event={event}
+                  />
+                ))}
               </div>
 
+              {/* Sentinel element for infinite scroll - only attach ref to this single element */}
```
Comment (Woldbye) [inline dashboard/src/app/(protected)/dashboard/[dashboardId]/events/EventLog.tsx]: Great idea to use a sentinel element!! 🔥 

Instead of the comment I would bind it to a variable and use that, as self-documenting code is always better:
```
const LoadMoreSentinel = <div ref={loadMoreRef} className='h-1' aria-hidden='true' />;
```

Then you can do `{hasNextPage && <LoadMoreSentinel />`

File: dashboard/src/app/(protected)/dashboard/[dashboardId]/events/EventLog.tsx [hunk 2]
```diff
@@ -96,20 +96,36 @@ export function EventLog({ pageSize = DEFAULT_PAGE_SIZE }: EventLogProps) {
     [data],
   );
 
-  const intersectionThreshold = Math.floor(pageSize / 2);
   const { ref: loadMoreRef, inView } = useInView<HTMLDivElement>({
     rootMargin: '100px',
     threshold: 0.1,
   });
 
+  // Use a ref to prevent duplicate fetches
```
Comment (Woldbye) [inline dashboard/src/app/(protected)/dashboard/[dashboardId]/events/EventLog.tsx]:
```suggestion
```

Comment doesn't seem to add any value here, its self explanatory! 👍

File: dashboard/src/app/(protected)/dashboard/[dashboardId]/events/EventLog.tsx [hunk 3]
```diff
@@ -96,20 +96,36 @@ export function EventLog({ pageSize = DEFAULT_PAGE_SIZE }: EventLogProps) {
...
     }
 
-    fetchNextPage();
+    isFetchingRef.current = true;
+    fetchNextPage().finally(() => {
+      // Reset the ref after a short delay to allow state updates
+      setTimeout(() => {
+        isFetchingRef.current = false;
+      }, 100);
+    });
```
[the remark this answers is not in the document]
Comment (evanyang1) [reply dashboard/src/app/(protected)/dashboard/[dashboardId]/events/EventLog.tsx]: I'm new to this code base. I'll continue to read the code base and get to know it, but Cursor did this one.

**Review by Woldbye — APPROVED** [review]
Looks good to me now! Approved 😀
